#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ -f ".env.final" ]]; then
  set -a
  # shellcheck disable=SC1091
  source ".env.final"
  set +a
fi

export WEB_DEFAULT_TOP_K="${WEB_DEFAULT_TOP_K:-12}"
export WEB_DEFAULT_OFFICIAL_ONLY="${WEB_DEFAULT_OFFICIAL_ONLY:-true}"
export WEB_DEFAULT_USE_LLM="${WEB_DEFAULT_USE_LLM:-true}"
export WEB_DEFAULT_LLM_BACKEND="${WEB_DEFAULT_LLM_BACKEND:-yandex_openai}"
export WEB_DEFAULT_EMBEDDINGS_RERANK="${WEB_DEFAULT_EMBEDDINGS_RERANK:-true}"
export WEB_DEFAULT_EMBEDDINGS_TOP_N="${WEB_DEFAULT_EMBEDDINGS_TOP_N:-80}"
export WEB_DEFAULT_SHOW_REASONING="${WEB_DEFAULT_SHOW_REASONING:-true}"
export WEB_DEFAULT_MULTI_STEP="${WEB_DEFAULT_MULTI_STEP:-true}"
export WEB_DEFAULT_ANSWER_MODE="${WEB_DEFAULT_ANSWER_MODE:-full}"
export WEB_DEFAULT_NORM_QUOTE="${WEB_DEFAULT_NORM_QUOTE:-true}"
export WEB_SERVER_NAME="${WEB_SERVER_NAME:-127.0.0.1}"
export WEB_SERVER_PORT="${WEB_SERVER_PORT:-7860}"
export ANSWER_CACHE_ENABLED="${ANSWER_CACHE_ENABLED:-true}"
export ANSWER_CACHE_TTL_SEC="${ANSWER_CACHE_TTL_SEC:-604800}"
export ANSWER_CACHE_MAX_ENTRIES="${ANSWER_CACHE_MAX_ENTRIES:-5000}"
export RETRIEVAL_CACHE_ENABLED="${RETRIEVAL_CACHE_ENABLED:-true}"
export RETRIEVAL_CACHE_TTL_SEC="${RETRIEVAL_CACHE_TTL_SEC:-259200}"
export RETRIEVAL_CACHE_MAX_ENTRIES="${RETRIEVAL_CACHE_MAX_ENTRIES:-10000}"
export YANDEX_CLOUD_MODEL="${YANDEX_CLOUD_MODEL:-yandexgpt-5-lite/latest}"

exec "./run.sh"
